In [1]:
!pip install scanpy

Collecting scanpy
  Downloading scanpy-1.11.5-py3-none-any.whl.metadata (9.3 kB)
Collecting anndata>=0.8 (from scanpy)
  Downloading anndata-0.12.7-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: h5py>=3.7.0 in /opt/conda/lib/python3.11/site-packages (from scanpy) (3.10.0)
Requirement already satisfied: joblib in /opt/conda/lib/python3.11/site-packages (from scanpy) (1.3.2)
Collecting legacy-api-wrap>=1.4.1 (from scanpy)
  Downloading legacy_api_wrap-1.5-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: matplotlib>=3.7.5 in /opt/conda/lib/python3.11/site-packages (from scanpy) (3.8.0)
Collecting natsort (from scanpy)
  Downloading natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: networkx>=2.7.1 in /opt/conda/lib/python3.11/site-packages (from scanpy) (3.1)
Requirement already satisfied: numba!=0.62.0rc1,>=0.57.1 in /opt/conda/lib/python3.11/site-packages (from scanpy) (0.57.1)
Requirement already satisfied: numpy>=1.24.1 in /opt/conda/lib/python3.11/site-packages (from scanpy) (1.24.4)
Requirement already satisfied: packaging>=21.3 in /opt/conda/lib/python3.11/site-packages (from scanpy) (23.2)
Requirement already satisfied: pandas>=1.5.3 in /opt/conda/lib/python3.11/site-packages (from scanpy) (2.1.1)
Requirement already satisfied: patsy!=1.0.0 in /opt/conda/lib/python3.11/site-packages (from scanpy) (0.5.3)
Collecting pynndescent>=0.5.13 (from scanpy)
  Downloading pynndescent-0.6.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: scikit-learn>=1.1.3 in /opt/conda/lib/python3.11/site-packages (from scanpy) (1.3.1)
Requirement already satisfied: scipy>=1.8.1 in /opt/conda/lib/python3.11/site-packages (from scanpy) (1.11.3)
Collecting seaborn>=0.13.2 (from scanpy)
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting session-info2 (from scanpy)
  Downloading session_info2-0.3-py3-none-any.whl.metadata (3.5 kB)
Collecting statsmodels>=0.14.5 (from scanpy)
  Downloading statsmodels-0.14.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from scanpy) (4.66.1)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.11/site-packages (from scanpy) (4.8.0)
Collecting umap-learn>=0.5.6 (from scanpy)
  Downloading umap_learn-0.5.11-py3-none-any.whl.metadata (26 kB)
Collecting array-api-compat>=1.7.1 (from anndata>=0.8->scanpy)
  Downloading array_api_compat-1.13.0-py3-none-any.whl.metadata (2.5 kB)
Collecting numpy>=1.24.1 (from scanpy)
  Downloading numpy-2.4.1-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting packaging>=21.3 (from scanpy)
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting scipy>=1.8.1 (from scanpy)
  Downloading scipy-1.17.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 41.9 MB/s eta 0:00:00
Collecting zarr!=3.0.*,>=2.18.7 (from anndata>=0.8->scanpy)
  Downloading zarr-3.1.5-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7.5->scanpy) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7.5->scanpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7.5->scanpy) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7.5->scanpy) (1.4.5)
Collecting numpy>=1.24.1 (from scanpy)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 42.6 MB/s eta 0:00:00
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7.5->scanpy) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7.5->scanpy) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.7.5->scanpy) (2.8.2)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in /opt/conda/lib/python3.11/site-packages (from numba!=0.62.0rc1,>=0.57.1->scanpy) (0.40.1)
INFO: pip is looking at multiple versions of numba to determine which version is compatible with other requirements. This could take a while.
Collecting numba!=0.62.0rc1,>=0.57.1 (from scanpy)
  Downloading numba-0.63.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Collecting llvmlite<0.47,>=0.46.0dev0 (from numba!=0.62.0rc1,>=0.57.1->scanpy)
  Downloading llvmlite-0.46.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas>=1.5.3->scanpy) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas>=1.5.3->scanpy) (2023.3)
Requirement already satisfied: six in /opt/conda/lib/python3.11/site-packages (from patsy!=1.0.0->scanpy) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn>=1.1.3->scanpy) (3.2.0)
Collecting patsy!=1.0.0 (from scanpy)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting scikit-learn>=1.1.3 (from scanpy)
  Downloading scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting donfig>=0.8 (from zarr!=3.0.*,>=2.18.7->anndata>=0.8->scanpy)
  Downloading donfig-0.8.1.post1-py3-none-any.whl.metadata (5.0 kB)
Collecting google-crc32c>=1.5 (from zarr!=3.0.*,>=2.18.7->anndata>=0.8->scanpy)
  Downloading google_crc32c-1.8.0-cp311-cp311-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (1.7 kB)
Collecting numcodecs>=0.14 (from zarr!=3.0.*,>=2.18.7->anndata>=0.8->scanpy)
  Downloading numcodecs-0.16.5-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Collecting typing-extensions (from scanpy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.11/site-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata>=0.8->scanpy) (6.0.1)
Downloading scanpy-1.11.5-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 176.4 MB/s eta 0:00:00
Downloading anndata-0.12.7-py3-none-any.whl (174 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.2/174.2 kB 101.3 MB/s eta 0:00:00
Downloading legacy_api_wrap-1.5-py3-none-any.whl (10 kB)
Downloading numba-0.63.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 98.1 MB/s eta 0:00:00:00:01
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 201.8 MB/s eta 0:00:0000:0100:01
Downloading packaging-25.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 43.4 MB/s eta 0:00:00
Downloading pynndescent-0.6.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 50.4 MB/s eta 0:00:00
Downloading scipy-1.17.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.1/35.1 MB 112.1 MB/s eta 0:00:0000:0100:01
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 124.1 MB/s eta 0:00:00
Downloading statsmodels-0.14.6-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 64.2 MB/s eta 0:00:00 0:00:01m
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB 113.6 MB/s eta 0:00:00
Downloading umap_learn-0.5.11-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.9/90.9 kB 60.3 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 74.5 MB/s eta 0:00:00a 0:00:01
Downloading natsort-8.4.0-py3-none-any.whl (38 kB)
Downloading session_info2-0.3-py3-none-any.whl (17 kB)
Downloading array_api_compat-1.13.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 kB 42.7 MB/s eta 0:00:00
Downloading llvmlite-0.46.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 100.3 MB/s eta 0:00:0000:0100:01
Downloading zarr-3.1.5-py3-none-any.whl (284 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.1/284.1 kB 120.6 MB/s eta 0:00:00
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 30.6 MB/s eta 0:00:00
Downloading donfig-0.8.1.post1-py3-none-any.whl (21 kB)
Downloading google_crc32c-1.8.0-cp311-cp311-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (33 kB)
Downloading numcodecs-0.16.5-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 168.8 MB/s eta 0:00:00a 0:00:01
Installing collected packages: typing-extensions, session-info2, packaging, numpy, natsort, llvmlite, legacy-api-wrap, google-crc32c, donfig, array-api-compat, scipy, patsy, numcodecs, numba, zarr, statsmodels, scikit-learn, seaborn, pynndescent, anndata, umap-learn, scanpy
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.8.0
    Uninstalling typing_extensions-4.8.0:
      Successfully uninstalled typing_extensions-4.8.0
  Attempting uninstall: packaging
    Found existing installation: packaging 23.2
    Uninstalling packaging-23.2:
      Successfully uninstalled packaging-23.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.40.1
    Uninstalling llvmlite-0.40.1:
      Successfully uninstalled llvmlite-0.40.1
  Attempting uninstall: scipy
    Found existing installation: scipy 1.11.3
    Uninstalling scipy-1.11.3:
      Successfully uninstalled scipy-1.11.3
  Attempting uninstall: patsy
    Found existing installation: patsy 0.5.3
    Uninstalling patsy-0.5.3:
      Successfully uninstalled patsy-0.5.3
  Attempting uninstall: numba
    Found existing installation: numba 0.57.1
    Uninstalling numba-0.57.1:
      Successfully uninstalled numba-0.57.1
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.14.0
    Uninstalling statsmodels-0.14.0:
      Successfully uninstalled statsmodels-0.14.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.1
    Uninstalling scikit-learn-1.3.1:
      Successfully uninstalled scikit-learn-1.3.1
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.13.0
    Uninstalling seaborn-0.13.0:
      Successfully uninstalled seaborn-0.13.0
Successfully installed anndata-0.12.7 array-api-compat-1.13.0 donfig-0.8.1.post1 google-crc32c-1.8.0 legacy-api-wrap-1.5 llvmlite-0.46.0 natsort-8.4.0 numba-0.63.1 numcodecs-0.16.5 numpy-1.26.4 packaging-25.0 patsy-1.0.2 pynndescent-0.6.0 scanpy-1.11.5 scikit-learn-1.8.0 scipy-1.17.0 seaborn-0.13.2 session-info2-0.3 statsmodels-0.14.6 typing-extensions-4.15.0 umap-learn-0.5.11 zarr-3.1.5

In [2]:
!pip install humanize

Collecting humanize
  Downloading humanize-4.15.0-py3-none-any.whl.metadata (7.8 kB)
Downloading humanize-4.15.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 15.1 MB/s eta 0:00:00
Installing collected packages: humanize
Successfully installed humanize-4.15.0

In [3]:
!pip install anndata

Requirement already satisfied: anndata in /opt/conda/lib/python3.11/site-packages (0.12.7)
Requirement already satisfied: array-api-compat>=1.7.1 in /opt/conda/lib/python3.11/site-packages (from anndata) (1.13.0)
Requirement already satisfied: h5py>=3.8 in /opt/conda/lib/python3.11/site-packages (from anndata) (3.10.0)
Requirement already satisfied: legacy-api-wrap in /opt/conda/lib/python3.11/site-packages (from anndata) (1.5)
Requirement already satisfied: natsort in /opt/conda/lib/python3.11/site-packages (from anndata) (8.4.0)
Requirement already satisfied: numpy>=1.26 in /opt/conda/lib/python3.11/site-packages (from anndata) (1.26.4)
Requirement already satisfied: packaging>=24.2 in /opt/conda/lib/python3.11/site-packages (from anndata) (25.0)
Requirement already satisfied: pandas!=2.1.2,<3,>=2.1.0 in /opt/conda/lib/python3.11/site-packages (from anndata) (2.1.1)
Requirement already satisfied: scipy>=1.12 in /opt/conda/lib/python3.11/site-packages (from anndata) (1.17.0)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in /opt/conda/lib/python3.11/site-packages (from anndata) (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2023.3)
Requirement already satisfied: donfig>=0.8 in /opt/conda/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /opt/conda/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in /opt/conda/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata) (0.16.5)
Requirement already satisfied: typing-extensions>=4.9 in /opt/conda/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata) (4.15.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.11/site-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata) (6.0.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.2,<3,>=2.1.0->anndata) (1.16.0)

In [4]:
!pip install git+https://github.com/gillislab/pyMN#egg=pymetaneighbor

Collecting pymetaneighbor
  Cloning https://github.com/gillislab/pyMN to /tmp/pip-install-u3qoad6w/pymetaneighbor_9aaa17e5efe04956944896808a9923cc
  Running command git clone --filter=blob:none --quiet https://github.com/gillislab/pyMN /tmp/pip-install-u3qoad6w/pymetaneighbor_9aaa17e5efe04956944896808a9923cc
  Resolved https://github.com/gillislab/pyMN to commit 882b54512347be66000f7909271fd8e0cb7def39
  Preparing metadata (setup.py) ... done
Requirement already satisfied: anndata>=0.7 in /opt/conda/lib/python3.11/site-packages (from pymetaneighbor) (0.12.7)
Requirement already satisfied: matplotlib>=3.1.2 in /opt/conda/lib/python3.11/site-packages (from pymetaneighbor) (3.8.0)
Requirement already satisfied: pandas>=0.21 in /opt/conda/lib/python3.11/site-packages (from pymetaneighbor) (2.1.1)
Requirement already satisfied: scipy>=1.4 in /opt/conda/lib/python3.11/site-packages (from pymetaneighbor) (1.17.0)
Requirement already satisfied: seaborn>=0.9.1 in /opt/conda/lib/python3.11/site-packages (from pymetaneighbor) (0.13.2)
Requirement already satisfied: scanpy in /opt/conda/lib/python3.11/site-packages (from pymetaneighbor) (1.11.5)
Requirement already satisfied: bottleneck in /opt/conda/lib/python3.11/site-packages (from pymetaneighbor) (1.3.7)
Requirement already satisfied: networkx in /opt/conda/lib/python3.11/site-packages (from pymetaneighbor) (3.1)
Collecting upsetplot (from pymetaneighbor)
  Downloading UpSetPlot-0.9.0.tar.gz (23 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: array-api-compat>=1.7.1 in /opt/conda/lib/python3.11/site-packages (from anndata>=0.7->pymetaneighbor) (1.13.0)
Requirement already satisfied: h5py>=3.8 in /opt/conda/lib/python3.11/site-packages (from anndata>=0.7->pymetaneighbor) (3.10.0)
Requirement already satisfied: legacy-api-wrap in /opt/conda/lib/python3.11/site-packages (from anndata>=0.7->pymetaneighbor) (1.5)
Requirement already satisfied: natsort in /opt/conda/lib/python3.11/site-packages (from anndata>=0.7->pymetaneighbor) (8.4.0)
Requirement already satisfied: numpy>=1.26 in /opt/conda/lib/python3.11/site-packages (from anndata>=0.7->pymetaneighbor) (1.26.4)
Requirement already satisfied: packaging>=24.2 in /opt/conda/lib/python3.11/site-packages (from anndata>=0.7->pymetaneighbor) (25.0)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in /opt/conda/lib/python3.11/site-packages (from anndata>=0.7->pymetaneighbor) (3.1.5)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.1.2->pymetaneighbor) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.1.2->pymetaneighbor) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.1.2->pymetaneighbor) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.1.2->pymetaneighbor) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.1.2->pymetaneighbor) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.1.2->pymetaneighbor) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.11/site-packages (from matplotlib>=3.1.2->pymetaneighbor) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas>=0.21->pymetaneighbor) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas>=0.21->pymetaneighbor) (2023.3)
Requirement already satisfied: joblib in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (1.3.2)
Requirement already satisfied: numba!=0.62.0rc1,>=0.57.1 in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (0.63.1)
Requirement already satisfied: patsy!=1.0.0 in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (1.0.2)
Requirement already satisfied: pynndescent>=0.5.13 in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (0.6.0)
Requirement already satisfied: scikit-learn>=1.1.3 in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (1.8.0)
Requirement already satisfied: session-info2 in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (0.3)
Requirement already satisfied: statsmodels>=0.14.5 in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (0.14.6)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (4.66.1)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (4.15.0)
Requirement already satisfied: umap-learn>=0.5.6 in /opt/conda/lib/python3.11/site-packages (from scanpy->pymetaneighbor) (0.5.11)
Requirement already satisfied: llvmlite<0.47,>=0.46.0dev0 in /opt/conda/lib/python3.11/site-packages (from numba!=0.62.0rc1,>=0.57.1->scanpy->pymetaneighbor) (0.46.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.1.2->pymetaneighbor) (1.16.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/conda/lib/python3.11/site-packages (from scikit-learn>=1.1.3->scanpy->pymetaneighbor) (3.2.0)
Requirement already satisfied: donfig>=0.8 in /opt/conda/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.7->pymetaneighbor) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /opt/conda/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.7->pymetaneighbor) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in /opt/conda/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.7->pymetaneighbor) (0.16.5)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.11/site-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata>=0.7->pymetaneighbor) (6.0.1)
Building wheels for collected packages: pymetaneighbor, upsetplot
  Building wheel for pymetaneighbor (setup.py) ... done
  Created wheel for pymetaneighbor: filename=pyMetaNeighbor-0.1.0-py3-none-any.whl size=29125 sha256=448f98b6df0cbcef187fba1897a6f4738bb0a0765bcba70c16cf792e0b25380e
  Stored in directory: /tmp/pip-ephem-wheel-cache-tevln2t0/wheels/81/4f/2f/ceba31de0b80b66b66844e8aa5fa3604b0f9754c5331b4a80e
  Building wheel for upsetplot (pyproject.toml) ... done
  Created wheel for upsetplot: filename=upsetplot-0.9.0-py3-none-any.whl size=24866 sha256=fe565a785a2c1a0a19731d481919acc066ed941177003456e827c5c57a9704a4
  Stored in directory: /home/jovyan/.cache/pip/wheels/7b/ce/88/1d0bce5b2680165c29c3e68416325e79674d5a9f422d037996
Successfully built pymetaneighbor upsetplot
Installing collected packages: upsetplot, pymetaneighbor
Successfully installed pymetaneighbor-0.1.0 upsetplot-0.9.0

In [6]:
import numpy as np
import pandas as pd
import scanpy as sc
import pymn
import anndata as ad
import scipy.sparse as sp
import time
import os
import gc
import sys
import resource
import time
import datetime
import multiprocessing

In [7]:
base_data_folder = "/sbgenomics/project-files/external_datasets/cellxgene/"

In [8]:
internal_dataset_study_id = "GEN_A2"
target_h5ad = "/sbgenomics/project-files/GEN_A2/250917_GEN_A2/GEN_A2_pass3.h5ad" #GEN_A2 run
#target_h5ad = "/sbgenomics/project-files/GEN_A1/GEN_A1_pass2.h5ad"
#result_folder = "/sbgenomics/output-files/GEN_A1_pass2.five_PFC_himem.level3." + str(round(time.time()))
result_folder = "/sbgenomics/output-files/GEN_A2_five_PFC_himem.pass3.level3." + str(round(time.time()))
#result_folder = "/sbgenomics/output-files/GEN_A3_motor_nuc_to_prefrontal.cellxgene." + str(round(time.time()))

In [9]:
os.mkdir(result_folder)
print(result_folder)

/sbgenomics/output-files/GEN_A1_pass2.five_PFC_himem.level3.1768252376

In [10]:
start_time = time.time()

In [ ]:
cortical_data = sc.read_h5ad("/sbgenomics/project-files/cortex_references_human_downsampled.Jan2026.h5ad")

In [11]:
cortical_data

AnnData object with n_obs × n_vars = 1251349 × 15112
    obs: 'assay_ontology_term_id', 'cell_type_ontology_term_id', 'development_stage_ontology_term_id', 'disease_ontology_term_id', 'self_reported_ethnicity_ontology_term_id', 'sex_ontology_term_id', 'tissue_ontology_term_id', 'donor_id', 'suspension_type', 'is_primary_data', 'tissue_type', 'cell_type', 'assay', 'disease', 'sex', 'tissue', 'self_reported_ethnicity', 'development_stage', 'observation_joinid', 'level_1', 'level_2', 'level_3', 'study_id'

In [12]:
cortical_data.obs["cell_type"].value_counts()

cell_type
Oligo                                  323839
Astro                                  105671
L2/3 IT                                 85534
EN                                      81931
OPC                                     54227
                                        ...
SST NPY                                   100
Miscellaneous                              78
EN_L5_ET                                   70
Vascular                                   19
Committed oligodendrocyte precursor        16
Name: count, Length: 84, dtype: int64

In [11]:
internal_dataset = sc.read_h5ad(target_h5ad, backed="r")  # Open in read mode without loading everything

In [13]:
internal_dataset.obs

,Batch,prep,rep,set,final_filt,individualID,Source,libraryID,Channel,n_genes,...,mito_genes,mito_ribo,ribo_genes,apoptosis,class,subclass,subtype,doublet_score,pred_dbl,demux_type
barcodekey,,,,,,,,,,,,,,,,,,,,,
NPSAD_20201103_A2_cDNA_AAACCCAAGAGCATCG,NPSAD_20201103_A2_cDNA,A,2,NPSAD_20201103_A,True,AMPAD_MSSM_0000048992,MSSM,AMPAD_MSSM_0000048992_2,AMPAD_MSSM_0000048992,4994,...,1.567117,0.052646,-0.065156,-0.121038,5,5_4,5_4_1,0.046952,False,singlet
NPSAD_20201103_A2_cDNA_AAACCCAAGATACCAA,NPSAD_20201103_A2_cDNA,A,2,NPSAD_20201103_A,True,AMPAD_HBCC_0000000027,HBCC,AMPAD_HBCC_0000000027_2,AMPAD_HBCC_0000000027,2552,...,0.112530,0.428618,0.684028,0.037632,1,1_2,1_2_1,0.013710,False,singlet
NPSAD_20201103_A2_cDNA_AAACCCAAGCAACAGC,NPSAD_20201103_A2_cDNA,A,2,NPSAD_20201103_A,True,AMPAD_MSSM_0000047108,MSSM,AMPAD_MSSM_0000047108_2,AMPAD_MSSM_0000047108,4633,...,0.343105,-0.024694,-0.318562,-0.012874,3,3_1,3_1_1,0.015699,False,singlet
NPSAD_20201103_A2_cDNA_AAACCCAAGCAATAAC,NPSAD_20201103_A2_cDNA,A,2,NPSAD_20201103_A,True,AMPAD_MSSM_0000047108,MSSM,AMPAD_MSSM_0000047108_2,AMPAD_MSSM_0000047108,2469,...,0.921847,0.097749,0.043935,-0.174334,1,1_2,1_2_4,0.040765,False,singlet
NPSAD_20201103_A2_cDNA_AAACCCAAGCACTAGG,NPSAD_20201103_A2_cDNA,A,2,NPSAD_20201103_A,False,AMPAD_MSSM_0000009374,MSSM,AMPAD_MSSM_0000009374_2,AMPAD_MSSM_0000009374,1363,...,0.577345,-0.079011,-0.117925,0.055481,1,1_2,1_2_1,0.022605,False,singlet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NPSAD_20201103_C2_cDNA_TTTGTTGGTGGTCAAG,NPSAD_20201103_C2_cDNA,C,2,NPSAD_20201103_C,True,AMPAD_MSSM_0000007105,MSSM,AMPAD_MSSM_0000007105_2,AMPAD_MSSM_0000007105,2379,...,0.173490,0.069410,0.053173,-0.100825,5,5_2,5_2_2,0.006263,False,singlet
NPSAD_20201103_C2_cDNA_TTTGTTGTCCCAACTC,NPSAD_20201103_C2_cDNA,C,2,NPSAD_20201103_C,True,AMPAD_MSSM_0000076286,MSSM,AMPAD_MSSM_0000076286_2,AMPAD_MSSM_0000076286,3938,...,0.257179,-0.043267,0.303214,0.160654,1,1_2,1_2_1,0.061601,False,singlet
NPSAD_20201103_C2_cDNA_TTTGTTGTCGCCTCTA,NPSAD_20201103_C2_cDNA,C,2,NPSAD_20201103_C,True,AMPAD_MSSM_0000079891,MSSM,AMPAD_MSSM_0000079891_2,AMPAD_MSSM_0000079891,3214,...,0.177684,0.198266,0.045670,-0.095239,4,4_3,4_3_3,0.016938,False,singlet
NPSAD_20201103_C2_cDNA_TTTGTTGTCTAGTCAG,NPSAD_20201103_C2_cDNA,C,2,NPSAD_20201103_C,True,AMPAD_MSSM_0000076286,MSSM,AMPAD_MSSM_0000076286_2,AMPAD_MSSM_0000076286,3920,...,0.147395,-0.071396,-0.302191,-0.082595,4,4_4,4_4_3,0.028450,False,singlet
NPSAD_20201103_C2_cDNA_TTTGTTGTCTGAGTCA,NPSAD_20201103_C2_cDNA,C,2,NPSAD_20201103_C,False,AMPAD_MSSM_0000079891,MSSM,AMPAD_MSSM_0000079891_2,AMPAD_MSSM_0000079891,5052,...,2.272134,0.025427,-0.180477,-0.112582,6,6_2,6_2_1,0.010327,False,singlet

In [14]:
## Create a new AnnData object with only the raw matrix
internal_dataset = sc.AnnData(internal_dataset.raw.X, obs=internal_dataset.obs, var=internal_dataset.var)
internal_dataset = internal_dataset.to_memory()

In [15]:
internal_dataset.obs.demux_type.unique()

['singlet']
Categories (1, object): ['singlet']

In [55]:
internal_dataset

AnnData object with n_obs × n_vars = 7933311 × 35766
    obs: 'Batch', 'prep', 'rep', 'set', 'final_filt', 'individualID', 'Source', 'libraryID', 'Channel', 'n_genes', 'n_counts', 'percent_mito', 'passed_qc', 'G1/S', 'G2/M', 'cycle_diff', 'cycling', 'predicted_phase', 'female_score', 'male_score', 'gender_score', 'predicted_gender', 'mito_genes', 'mito_ribo', 'ribo_genes', 'apoptosis', 'class', 'subclass', 'subtype', 'doublet_score', 'pred_dbl', 'demux_type', 'cell_type', 'level_1', 'level_2', 'level_3', 'study_id'
    var: 'gene_symbols', 'feature_types', 'gene_name', 'gene_type', 'gene_chrom', 'gene_start', 'gene_end', 'n_cells', 'percent_cells', 'robust', 'highly_variable_features', 'ribo', 'mito', 'protein_coding', 'mitocarta', 'robust_protein_coding', 'robust_protein_coding_autosome', 'mean', 'bins'

In [ ]:
#internal_dataset.obs["cell_type"].value_counts()

In [16]:
internal_dataset.var = internal_dataset.var.set_index("gene_id")

In [17]:
internal_dataset.var

,gene_symbols,feature_types,gene_name,gene_type,gene_chrom,gene_start,gene_end,n_cells,percent_cells,robust,highly_variable_features,ribo,mito,protein_coding,mitocarta,robust_protein_coding,robust_protein_coding_autosome,mean,bins
gene_id,,,,,,,,,,,,,,,,,,,
ENSG00000186827,TNFRSF4,protein_coding,TNFRSF4,protein_coding,1,1211340,1214153,38365,0.431327,True,False,False,False,True,False,True,True,0.001733,"(0.00151, 0.00176]"
ENSG00000186891,TNFRSF18,protein_coding,TNFRSF18,protein_coding,1,1203508,1206592,53023,0.596123,True,False,False,False,True,False,True,True,0.002133,"(0.00206, 0.0024]"
ENSG00000160072,ATAD3B,protein_coding,ATAD3B,protein_coding,1,1471765,1497848,1454258,16.349824,True,False,False,False,True,True,False,False,0.080050,"(0.0758, 0.0878]"
ENSG00000041988,THAP3,protein_coding,THAP3,protein_coding,1,6624866,6635586,679062,7.634508,True,False,False,False,True,False,True,True,0.037893,"(0.0358, 0.0417]"
ENSG00000260179,NaN,lncRNA,ENSG00000260179,lncRNA,1,1249777,1251334,8362,0.094012,True,False,False,False,False,False,False,False,0.000401,"(0.000342, 0.00041]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000278817,NaN,protein_coding,ENSG00000278817,protein_coding,KI270734.1,131494,137392,208980,2.349505,True,False,False,False,True,False,True,False,0.010444,"(0.0101, 0.0119]"
ENSG00000278384,NaN,protein_coding,ENSG00000278384,protein_coding,GL000218.1,51867,54893,240690,2.706012,True,False,False,False,True,False,True,False,0.012234,"(0.0119, 0.0139]"
ENSG00000276345,NaN,protein_coding,ENSG00000276345,protein_coding,KI270721.1,2585,11802,34268,0.385266,True,False,False,False,True,False,True,False,0.001703,"(0.00151, 0.00176]"
ENSG00000271254,NaN,protein_coding,ENSG00000271254,protein_coding,KI270711.1,4612,29626,763612,8.585080,True,False,False,False,True,False,True,False,0.042609,"(0.0417, 0.0486]"
ENSG00000275405,NaN,snRNA,ENSG00000275405,snRNA,KI270713.1,21861,22024,17104,0.192296,True,False,False,False,False,False,False,False,0.000692,"(0.000671, 0.000794]"

In [18]:
# Create cell_type column
internal_dataset.obs['cell_type'] = internal_dataset.obs['subtype'] #or class
internal_dataset.obs['level_1'] = internal_dataset.obs['class'] #or class
internal_dataset.obs['level_2'] = internal_dataset.obs['subclass']
internal_dataset.obs['level_3'] = internal_dataset.obs['subtype'] #or class
internal_dataset.obs['study_id'] = internal_dataset_study_id

In [19]:
internal_dataset.var

,gene_symbols,feature_types,gene_name,gene_type,gene_chrom,gene_start,gene_end,n_cells,percent_cells,robust,highly_variable_features,ribo,mito,protein_coding,mitocarta,robust_protein_coding,robust_protein_coding_autosome,mean,bins
gene_id,,,,,,,,,,,,,,,,,,,
ENSG00000186827,TNFRSF4,protein_coding,TNFRSF4,protein_coding,1,1211340,1214153,38365,0.431327,True,False,False,False,True,False,True,True,0.001733,"(0.00151, 0.00176]"
ENSG00000186891,TNFRSF18,protein_coding,TNFRSF18,protein_coding,1,1203508,1206592,53023,0.596123,True,False,False,False,True,False,True,True,0.002133,"(0.00206, 0.0024]"
ENSG00000160072,ATAD3B,protein_coding,ATAD3B,protein_coding,1,1471765,1497848,1454258,16.349824,True,False,False,False,True,True,False,False,0.080050,"(0.0758, 0.0878]"
ENSG00000041988,THAP3,protein_coding,THAP3,protein_coding,1,6624866,6635586,679062,7.634508,True,False,False,False,True,False,True,True,0.037893,"(0.0358, 0.0417]"
ENSG00000260179,NaN,lncRNA,ENSG00000260179,lncRNA,1,1249777,1251334,8362,0.094012,True,False,False,False,False,False,False,False,0.000401,"(0.000342, 0.00041]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000278817,NaN,protein_coding,ENSG00000278817,protein_coding,KI270734.1,131494,137392,208980,2.349505,True,False,False,False,True,False,True,False,0.010444,"(0.0101, 0.0119]"
ENSG00000278384,NaN,protein_coding,ENSG00000278384,protein_coding,GL000218.1,51867,54893,240690,2.706012,True,False,False,False,True,False,True,False,0.012234,"(0.0119, 0.0139]"
ENSG00000276345,NaN,protein_coding,ENSG00000276345,protein_coding,KI270721.1,2585,11802,34268,0.385266,True,False,False,False,True,False,True,False,0.001703,"(0.00151, 0.00176]"
ENSG00000271254,NaN,protein_coding,ENSG00000271254,protein_coding,KI270711.1,4612,29626,763612,8.585080,True,False,False,False,True,False,True,False,0.042609,"(0.0417, 0.0486]"
ENSG00000275405,NaN,snRNA,ENSG00000275405,snRNA,KI270713.1,21861,22024,17104,0.192296,True,False,False,False,False,False,False,False,0.000692,"(0.000671, 0.000794]"

In [20]:
merged=ad.concat([cortical_data, internal_dataset], join="inner")

In [21]:
merged

AnnData object with n_obs × n_vars = 9184660 × 15112
    obs: 'cell_type', 'level_1', 'level_2', 'level_3', 'study_id'

In [22]:
merged.obs['cell_type'] = merged.obs['cell_type'].to_numpy(dtype="str")
merged.obs['study_id'] = merged.obs['study_id'].to_numpy(dtype="str")
merged.obs['level_1'] = merged.obs['level_1'].to_numpy(dtype="str")
merged.obs['level_2'] = merged.obs['level_2'].to_numpy(dtype="str")
merged.obs['level_3'] = merged.obs['level_3'].to_numpy(dtype="str")
merged.obs.index = merged.obs.index.to_numpy(dtype="str")

In [23]:
#merged.write("/sbgenomics/output-files/GEN_A1_pass2_cortex_merged.Nov2025.full.h5ad")
#merged.write("/sbgenomics/output-files/GEN_A1_pass2_merged_three_references.Nov2025.full.h5ad")
#print("DOne write")

In [24]:
pymn.variableGenes(merged, study_col='study_id')

In [25]:
sum(merged.var.highly_variable)

786

In [26]:
#subset to highly variable genes to free up memory
merged = merged[:, merged.var.highly_variable]

In [27]:
#use numpy types instead of pandas
merged.var.highly_variable = merged.var.highly_variable.to_numpy(dtype="bool")
merged.var.index = merged.var.index.to_numpy(dtype="str")

/opt/conda/lib/python3.11/site-packages/pandas/core/generic.py:6234: ImplicitModificationWarning: Trying to modify attribute `.var` of view, initializing view as actual.
  self[name] = value

In [28]:
#make cell indices unique
merged.obs_names_make_unique()

In [29]:
merged.obs['cell_type'] = merged.obs['cell_type'].to_numpy(dtype="str")
merged.obs['study_id'] = merged.obs['study_id'].to_numpy(dtype="str")
merged.obs.index = merged.obs.index.to_numpy(dtype="str")

In [30]:
merged

AnnData object with n_obs × n_vars = 9184660 × 786
    obs: 'cell_type', 'level_1', 'level_2', 'level_3', 'study_id'
    var: 'highly_variable'

In [31]:
#merged = sc.read_h5ad("/sbgenomics/project-files/GEN_A1/GEN_A1_pass2_merged_three_references.Nov2025.full.h5ad")

In [32]:
#merged = sc.read_h5ad("/sbgenomics/project-files/GEN_A1_pass2_merged_three_references.Nov2025.full.h5ad", backed='r')

# Get total number of cells
#n_cells = merged.n_obs

# Randomly select a third of the cells
#np.random.seed(42)  # Set seed for reproducibility
#random_indices = np.random.choice(n_cells, size=n_cells // 3, replace=False)
#random_indices = np.sort(random_indices)  # Sort for efficient access

# Subset to selected cells and load into memory
#merged = merged[random_indices, :].to_memory()

In [33]:
if "doublet_filtered" in result_folder:
    print("Filtering suspect doublets")
    df = pd.read_csv("/sbgenomics/project-files/python_Metaneighbor_runs/GEN_A2_three_PFC_himem.subtype.1745346351/top_hits.0.8.combined.curated.csv")
    # keep rows where Manual_agreement is False and pull the target column
    suspected_doublet_subtypes = set(df[~df["Manual_agreement"].fillna(True)]["Study_ID|Celltype_1"].tolist())
    #second round from 1 vs 1
    df = pd.read_csv("/sbgenomics/project-files/python_Metaneighbor_runs/GEN_A2_three_PFC_himem.subtype.doublet_filtered.1746553501/one_v_one.top_hits.combined.curated.csv")
    suspected_doublet_subtypes = suspected_doublet_subtypes.union(set(df[~df["Manual_agreement"].fillna(True)]["reference_name"].tolist()))
    
    print(suspected_doublet_subtypes)
    print(len(suspected_doublet_subtypes))
    
    mask = ~merged.obs['cell_type'].isin(suspected_doublet_subtypes)
    merged = merged[mask]

In [34]:
merged.obs['cell_type'] = merged.obs['cell_type'].to_numpy(dtype="str")
merged.obs['study_id'] = merged.obs['study_id'].to_numpy(dtype="str")
merged.obs['level_1'] = merged.obs['level_1'].to_numpy(dtype="str")
merged.obs['level_2'] = merged.obs['level_2'].to_numpy(dtype="str")
merged.obs['level_3'] = merged.obs['level_3'].to_numpy(dtype="str")
merged.obs.index = merged.obs.index.to_numpy(dtype="str")

In [35]:
print("test")

test

In [36]:
merged.obs

,cell_type,level_1,level_2,level_3,study_id
HSB106_1_AAACCCAAGAGGCGTT,Oligo,Glia,Oligo,Oligo MOG OPALIN,Ma_2022
HSB106_1_AAACCCAAGGTAGTCG,Oligo,Glia,Oligo,Oligo MOG OPALIN,Ma_2022
HSB106_1_AAACCCAAGGTTATAG,Oligo,Glia,Oligo,Oligo MOG OPALIN,Ma_2022
HSB106_1_AAACCCAAGTCGCCCA,L3-5 IT-1,ExN,L3-5 IT-1,L3-5 RORB PCBP3 IL1RAPL2,Ma_2022
HSB106_1_AAACCCACAAAGGAGA,L2-3 IT,ExN,L2-3 IT,L2-3 CUX2 ACVR1C THSD7A,Ma_2022
...,...,...,...,...,...
NPSAD_20201103_C2_cDNA_TTTGTTGGTGGTCAAG,6_2_2,6,6_2,6_2_2,GEN_A1
NPSAD_20201103_C2_cDNA_TTTGTTGTCCCAACTC,1_1_1,1,1_1,1_1_1,GEN_A1
NPSAD_20201103_C2_cDNA_TTTGTTGTCGCCTCTA,4_3_3,4,4_3,4_3_3,GEN_A1
NPSAD_20201103_C2_cDNA_TTTGTTGTCTAGTCAG,4_5_2,4,4_5,4_5_2,GEN_A1
NPSAD_20201103_C2_cDNA_TTTGTTGTCTGAGTCA,5_2_1,5,5_2,5_2_1,GEN_A1

In [37]:
#pymn.variableGenes(merged, study_col='study_id')

In [38]:
sum(merged.var.highly_variable)

786

In [39]:
#subset to highly variable genes to free up memory
#merged = merged[:, merged.var.highly_variable]

In [40]:
#use numpy types instead of pandas
merged.var.highly_variable = merged.var.highly_variable.to_numpy(dtype="bool")
merged.var.index = merged.var.index.to_numpy(dtype="str")

In [41]:
#make cell indices unique
merged.obs_names_make_unique()

In [42]:
merged.obs['cell_type'] = merged.obs['cell_type'].to_numpy(dtype="str")
merged.obs['study_id'] = merged.obs['study_id'].to_numpy(dtype="str")
merged.obs.index = merged.obs.index.to_numpy(dtype="str")

In [43]:
#%%time
#run
pymn.MetaNeighborUS(merged,
                    study_col='study_id',
                    ct_col='cell_type',
                    fast_version=True, symmetric_output=True)

/opt/conda/lib/python3.11/site-packages/pymn/MetaNeighborUS.py:62: FutureWarning: Use obs (e.g. `k in adata.obs` or `str(adata.obs.columns.tolist())`) instead of AnnData.obs_keys, AnnData.obs_keys is deprecated and will be removed in the future.
  assert study_col in adata.obs_keys(), "Study Col not in adata"
/opt/conda/lib/python3.11/site-packages/pymn/MetaNeighborUS.py:63: FutureWarning: Use obs (e.g. `k in adata.obs` or `str(adata.obs.columns.tolist())`) instead of AnnData.obs_keys, AnnData.obs_keys is deprecated and will be removed in the future.
  assert ct_col in adata.obs_keys(), "Cluster Col not in adata"
/opt/conda/lib/python3.11/site-packages/pymn/MetaNeighborUS.py:73: FutureWarning: Use var (e.g. `k in adata.var` or `str(adata.var.columns.tolist())`) instead of AnnData.var_keys, AnnData.var_keys is deprecated and will be removed in the future.
  var_genes in adata.var_keys()

In [44]:
print("After running metaneighbor all vs all")
aurocs = merged.uns["MetaNeighborUS"]
aurocs.to_csv(result_folder + "/aurocs_full.csv.gz", compression="gzip")

After running metaneighbor all vs all

In [45]:
#seems to crash here, not sure why - moved to python script
#run 1 vs best
pymn.MetaNeighborUS(merged,
                    study_col='study_id',
                    ct_col='cell_type', one_vs_best=True,
                    fast_version=True, symmetric_output=True)

/opt/conda/lib/python3.11/site-packages/pymn/MetaNeighborUS.py:62: FutureWarning: Use obs (e.g. `k in adata.obs` or `str(adata.obs.columns.tolist())`) instead of AnnData.obs_keys, AnnData.obs_keys is deprecated and will be removed in the future.
  assert study_col in adata.obs_keys(), "Study Col not in adata"
/opt/conda/lib/python3.11/site-packages/pymn/MetaNeighborUS.py:63: FutureWarning: Use obs (e.g. `k in adata.obs` or `str(adata.obs.columns.tolist())`) instead of AnnData.obs_keys, AnnData.obs_keys is deprecated and will be removed in the future.
  assert ct_col in adata.obs_keys(), "Cluster Col not in adata"
/opt/conda/lib/python3.11/site-packages/pymn/MetaNeighborUS.py:73: FutureWarning: Use var (e.g. `k in adata.var` or `str(adata.var.columns.tolist())`) instead of AnnData.var_keys, AnnData.var_keys is deprecated and will be removed in the future.
  var_genes in adata.var_keys()

In [46]:
aurocs = merged.uns["MetaNeighborUS_1v1"]
aurocs.to_csv(result_folder + "/aurocs_1v1.csv.gz", compression="gzip")

In [47]:
cell_counts = merged.obs.groupby("study_id").size()
cell_counts.to_csv(result_folder + "/cell_study_counts.csv")
cell_type_counts = merged.obs[["study_id", "cell_type"]].drop_duplicates().groupby("study_id").size()
cell_type_counts.to_csv(result_folder + "/cell_type_per_study_counts.csv")

In [48]:
for set_threshold in [0.8, 0.9, 0.95, 0.99, 0.999]:
    print(set_threshold)
    pymn.topHits(merged, threshold=set_threshold)
    tophit_table = merged.uns['MetaNeighborUS_topHits']
    tophit_table.to_csv(result_folder + "/top_hits."+str(set_threshold)+".csv")

0.8

/opt/conda/lib/python3.11/site-packages/pymn/topHits.py:33: FutureWarning: Use uns (e.g. `k in adata.uns` or `sorted(adata.uns)`) instead of AnnData.uns_keys, AnnData.uns_keys is deprecated and will be removed in the future.
  mn_key in adata.uns_keys()

0.9

/opt/conda/lib/python3.11/site-packages/pymn/topHits.py:33: FutureWarning: Use uns (e.g. `k in adata.uns` or `sorted(adata.uns)`) instead of AnnData.uns_keys, AnnData.uns_keys is deprecated and will be removed in the future.
  mn_key in adata.uns_keys()

0.95

/opt/conda/lib/python3.11/site-packages/pymn/topHits.py:33: FutureWarning: Use uns (e.g. `k in adata.uns` or `sorted(adata.uns)`) instead of AnnData.uns_keys, AnnData.uns_keys is deprecated and will be removed in the future.
  mn_key in adata.uns_keys()

0.99

/opt/conda/lib/python3.11/site-packages/pymn/topHits.py:33: FutureWarning: Use uns (e.g. `k in adata.uns` or `sorted(adata.uns)`) instead of AnnData.uns_keys, AnnData.uns_keys is deprecated and will be removed in the future.
  mn_key in adata.uns_keys()

0.999

/opt/conda/lib/python3.11/site-packages/pymn/topHits.py:33: FutureWarning: Use uns (e.g. `k in adata.uns` or `sorted(adata.uns)`) instead of AnnData.uns_keys, AnnData.uns_keys is deprecated and will be removed in the future.
  mn_key in adata.uns_keys()

In [49]:
merged.obs.to_csv(result_folder + "/merged.obs.csv.gz", compression="gzip")
merged.var.to_csv(result_folder + "/merged.var.csv.gz", compression="gzip")

In [50]:
#write number of unique genes per cell
if sp.issparse(merged.X):
    n_unique_genes = np.asarray((merged.X > 0).sum(axis=1)).ravel()
else:
    n_unique_genes = (merged.X > 0).sum(axis=1).astype(int)
merged.obs["n_unique_genes"] = n_unique_genes
merged.obs["celltype_study"] = (
    merged.obs["study_id"].astype(str) + "|" + merged.obs["cell_type"].astype(str)
)
avg_genes_per_group = (
    merged.obs.groupby("celltype_study")["n_unique_genes"].mean().sort_index()
)
print(avg_genes_per_group.head())
avg_genes_per_group.reset_index().to_csv(result_folder + "/avg_unique_genes_per_celltype_study.csv", index=False)

celltype_study
GEN_A1|10_1_1    197.867319
GEN_A1|10_1_2    190.688409
GEN_A1|10_1_3    196.059560
GEN_A1|10_1_4    183.121534
GEN_A1|10_2_1    219.315361
Name: n_unique_genes, dtype: float64

In [51]:
#write out peak memory at end
mem_usage = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
# print the memory usage in megabytes
print("Peak memory use in Gb  " + str(round(mem_usage / 1024 / 1024,2 )) + " PID  " + str(os.getpid()))

os.mkdir(os.path.join(result_folder, "Peak memory use in Gb " + str(round(mem_usage / 1024 / 1024 ,2))))

Peak memory use in Gb  1502.54 PID  973

In [52]:
end_time = time.time()
print("Time taken h_m_s " + str(datetime.timedelta(seconds=end_time-start_time)).replace(':', '_').split('.')[0])
os.mkdir(os.path.join(result_folder, "Time taken h_m_s " + str(datetime.timedelta(seconds=end_time-start_time)).replace(':', '_').split('.')[0]))

Time taken h_m_s 1_51_29

In [53]:
print("Done!")

Done!

In [54]:
result_folder

'/sbgenomics/output-files/GEN_A1_five_PFC_himem.pass3.level3.1763569714'